domains:
- domain: do.houyewei.com
  type: PRIMARY
name: sample-html
region: sgp
static_sites:
- build_command: npm run build
  environment_slug: html
  github:
    branch: master
    deploy_on_push: true
    repo: wynsto/sample-html
  name: sample-html
  routes:
  - path: /
  source_dir: /